server:
  port: 10000

netty:
  #  默认是我的名字，在26个字母里面对应的位置，6-10-13
  port: 61013
  ws: "ws://127.0.0.1:61013/ws"

spring:
  application:
    name: 'wechat-server-monolith'
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xue_gao_im_chat_v2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true

logging:
  level:
    root: info


xuegao:
  concurrent:
    # 开启为true，不开启则设置为false
    enable: true
    # 以下都有默认值，可以不设置
    # 线程池核心线程数
    corePoolSize: 16
    # 线程池最大线程数
    maximumPoolSize: 16
    # 超过核心线程数的线程的存活时间
    keepAliveTime: 30
    # 阻塞队列容量
    blockingQueueCapacity: 1024
    # 阻塞队列类型
    blockingQueueType: ARRAY_BLOCKING_QUEUE
    # 是否使用线程池并发执行查询
    concurrentActive: true



